
//   ****************************************************************************
//  ******************************************************************************
// ********************************************************************************
// **** ===========================================================================
// ****  Name     : CommonTransformDefs.h
// ****  Part of  : Transform
// ****  Created  : 09/12/2004 by Emanuele Cipolloni
// ****  Description:
// ****     Global definitions and constants for the application Transform.
// ****
// ****
// ****     Initial content was generated by eyeGT Creator.
// ****
// ****  Version  : 1.1
// ****  Copyright: (C) Copyright 2001-2004 by Barefoot Software Inc.
// **** ===========================================================================
// ********************************************************************************
//  ******************************************************************************
//   ****************************************************************************

#ifndef COMMONTRANSFORMDEFS_H_INCLUDED
#define COMMONTRANSFORMDEFS_H_INCLUDED

#include "eyeGTSym.h"
#include "objlist.h"
#include "objlist16.h"
#include "bf_StringUtils.h"
#include "bf_StringUtils16.h"

#include "eyeGT_Utilities.h"

#include "HeapStream.h"

#if defined(UNDER_SYMBIAN)
#include <libc/stdio.h>
#include <libc/stdlib.h>
#else
#include <stdlib.h>
#include <stdio.h>
#endif

#if !defined(_LIT)
#define _LIT(a,b) const char a[] = b
#endif
 

//add SWIDTH, & SHEIGHT and more PLATID to platforms
//check why it is slow at loading books in teh beginning

//Platform ID
#if defined(UNDER_SYMBIAN)
	#if defined(UNDER_SERIES60_2X)
	_LIT(PlatID, "S602X");
	#elif defined(UNDER_SERIES60_3X)
	_LIT(PlatID, "S603X");
	#elif defined(UNDER_UIQ_2X)
	_LIT(PlatID, "UIQ2X");
	#elif defined(UNDER_UIQ_3)
	_LIT(PlatID, "UIQ3");
	#endif
#elif defined(UNDER_CE) && (!defined(UNDER_SMARTPHONE2002))
		const char PlatID[] = "PPC";
#elif defined(UNDER_SMARTPHONE2002)
		const char PlatID[] = "SMP";
#elif defined(UNDER_WIN32)
		const char PlatID[] = "W32";
#elif defined(UNDER_PSP)
		const char PlatID[] = "PSP";
#endif

#if defined(UNDER_SYMBIAN)
_LIT(Version, "0100"); 
#else
const char Version[] = "0100";
#endif

//setup extension
#if defined(BUILD_TRANSFORM)

//The directories where all our stuff is stored
#if defined(UNDER_UIQ_3)
_LIT(KViewerDataDir,		"Shared");
_LIT(KViewerTransformDir,	"Transform");
_LIT(KViewerAssetsDir,		"Assets");

_LIT(KViewerAssets,		"\\Shared\\Transform\\Assets\\");

const char stViewerAssets[]	= "\\Shared\\Transform\\Assets\\";
#elif defined(UNDER_IPHONE)
const char stData[]		= "/";
const char stViewerAssets[]	= "/";
const char stViewerImages[]	= "/";
#else

_LIT(KViewerDataDir,		"Data");
_LIT(KViewerTransformDir,	"Transform");
_LIT(KViewerAssetsDir,		"Assets");

_LIT(KViewerAssets,		"\\Data\\Transform\\Assets\\");

const char stViewerAssets[]	= "\\Data\\Transform\\Assets\\";
const char stViewerImages[]	= "\\Data\\Transform\\Assets\\img\\";
#endif
#else
@define the Transform personalization
#endif


enum TMessagelimites {
	mlNormal			=  0,
	mlAuto				=  1
};

const int MessagesLimit[2] =
{
	3,
	3
};

const char NormalMsg[6][30] =
{
	"Change                      ",
	"Key 5 for Auto",
	"                        Exit"
};

const char AutoMsg[6][30] =
{
	"Auto                        ",
	"                        Exit"
};

#if defined(DEVICE_HAS_TOUCHSCREEN)
enum TToolbarButtons {
	tbExit		= 0x0001,
	tbAuto		= 0x0002,
	tbStop		= 0x0004,
	tbChange	= 0x0008
};

const U16 ToolbarConfig[2] =
{
	tbChange | tbAuto,	//mlNormal
	tbStop				//mlAuto
};
#endif

#endif //COMMONTRANSFORMDEFS_H_INCLUDED
// End of File
